### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [chingisdev/Async_API_sprint_2#29]
Отличная работа! Вы мололцы! Предложения по доработке:

1. Не используйте прямое указание кодов ответов сервера в тестах (200, 400 и т.д.), применяйте http.HTTPStatus. Этим можно немного повысить читаемость кода https://docs.python.org/3/library/http.html#http.HTTPStatus
2. С развитием проекта в тестах фикстур будет все больше и больше, и их нужно систематизировать. Можно вынести в отдельный файл (затем добавлять другие файлы, логически разделяя их) и тем самым облегчим [conftest.py](http://conftest.py/). Для этого есть [pytest_plugins](https://docs.pytest.org/en/latest/how-to/fixtures.html)
3. Находил несоответсвия PEP8. [Пример](https://github.com/chingisdev/Async_API_sprint_2/blob/main/tests/functional/conftest.py#L12), должно быть две пустые строки отступ. Рекомендую пользоваться линтерами. Пргоните проект через flake8, и он вам все покажет.
4. В docker-compose.yml много лишних портов выставлено наружу, достаточно только nginx. Для безопасности приложения это плохо.
5. В скриптах ожидания ES и Redis в тестах вместо вечного цикла, в который можно попасть при возникновении сложностей, лучше использовать backoff из прошлых спринтов. Он более функционален в сравнении с вечным циклом, теоретически он может сигнализировать команде поддержки после определенного количества попыток.
6. [Этот](https://github.com/chingisdev/Async_API_sprint_2/blob/main/tests/functional/src/test_get.py#L17) маркер можно указать один раз на уровне файла: https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.20.2/
7. Если у вас в теле теста есть хотя бы один [if](https://github.com/chingisdev/Async_API_sprint_2/blob/main/tests/functional/src/test_get.py#L19), то вы запихнули в один тест несколько кейсов. Так делать нельзя, идея теста в том, что простой линейный код тестирует сложный, так достигается некоторый уровень надежности. if и другие конструкции в теле теста усложняют его и в итоге вы на сложный код пишите сложный тест, который потом еще раз другим тестом придется покрывать :) В общем, разделите все тесты, в которых у вас есть if на несколько таким образом, чтобы у вас не осталось ни одного if в теле тестов
8. Я бы рекомендовал разделить названия модулей тестов не на get, search, а больше на названия самих ресурсов film, person, genre
9. Неплохо было бы также тестировать на 400 ошибки. Отправлять запрос с данными, которые не должны пройти валидацию и проверять что ответ от сервера 400 (запрос не прошел).
10. По [SOLID](https://github.com/chingisdev/Async_API_sprint_2/blob/main/movies_api/services/searchable_model_service.py) неплохо было бы сделать абстрактные классы еще для search и cache. Потом кокретную реализацию этих классов для redis и elasticsearch. Чтобы при переходе на другие движки было меньше проблем. Хороший пример [тут](https://qna.habr.com/q/744609)

**Comment by chingisdev** [comment]
Implemented suggestions
